security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        db_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: db_provider
            guard: 
                authenticators: # <- Corrected option name
                    - App\Security\GoogleAuthenticator # <- Indented properly
                    - App\Security\MyFacebookAuthenticator
                
            logout:
                path: "app_logout"
                target: "app_login"
    access_control:
        - { path: ^/admin, roles: ROLE_admin}

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
